-- Drop existing tables to ensure clean slate if rerunning
DROP TABLE IF EXISTS "public"."orders" CASCADE;
DROP TABLE IF EXISTS "public"."products" CASCADE;
DROP TABLE IF EXISTS "public"."customers" CASCADE;

-- CREATE PRODUCTS TABLE
CREATE TABLE "public"."products" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "category" text DEFAULT 'Uncategorized',
    "price" numeric(10,2) NOT NULL DEFAULT 0.00,
    "stock" integer NOT NULL DEFAULT 0,
    "status" text DEFAULT 'Draft',
    "image" text DEFAULT 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=200&h=200&fit=crop',
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- CREATE CUSTOMERS TABLE
CREATE TABLE "public"."customers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "email" text UNIQUE NOT NULL,
    "phone" text,
    "orders_count" integer DEFAULT 0,
    "spent" numeric(10,2) DEFAULT 0.00,
    "join_date" text,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- CREATE ORDERS TABLE
CREATE TABLE "public"."orders" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" bigint REFERENCES customers(id),
    "customer_name" text NOT NULL,
    "email" text NOT NULL,
    "total" numeric(10,2) NOT NULL DEFAULT 0.00,
    "status" text DEFAULT 'Pending',
    "items" integer DEFAULT 1,
    "payment_status" text DEFAULT 'Pending',
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SET UP ROW LEVEL SECURITY
ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

-- CREATE POLICIES TO ALLOW ALL OPERATIONS FOR THIS DEMONSTRATION
CREATE POLICY "Enable all operations for all users on products" ON "public"."products" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users on customers" ON "public"."customers" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users on orders" ON "public"."orders" FOR ALL USING (true) WITH CHECK (true);

-- INSERT INITIAL MOCK DATA
INSERT INTO "public"."products" ("name", "category", "price", "stock", "status", "image") VALUES
('Radiant Glow Serum', 'Skincare', 48.00, 124, 'Active', 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=200&h=200&fit=crop'),
('Velvet Matte Lipstick', 'Makeup', 24.00, 0, 'Out of Stock', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=200&h=200&fit=crop');

INSERT INTO "public"."customers" ("name", "email", "phone", "orders_count", "spent", "join_date") VALUES
('Emma Thompson', 'emma@example.com', '+1 234-567-8900', 12, 1245.00, 'Jan 15, 2025');

INSERT INTO "public"."orders" ("customer_id", "customer_name", "email", "total", "status", "items", "payment_status") VALUES
((SELECT "id" FROM "public"."customers" WHERE "email" = 'emma@example.com'), 'Emma Thompson', 'emma@example.com', 124.00, 'Pending', 3, 'Paid');
