-- CREATE PROMOS TABLE
CREATE TABLE "public"."promos" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" text UNIQUE NOT NULL,
    "discount_type" text NOT NULL,
    "discount_value" numeric(10,2) NOT NULL,
    "usage_count" integer DEFAULT 0,
    "status" text DEFAULT 'Active',
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- CREATE REVIEWS TABLE
CREATE TABLE "public"."reviews" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_name" text NOT NULL,
    "product_name" text NOT NULL,
    "rating" integer NOT NULL,
    "comment" text NOT NULL,
    "status" text DEFAULT 'Pending',
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SET UP ROW LEVEL SECURITY
ALTER TABLE "public"."promos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reviews" ENABLE ROW LEVEL SECURITY;

-- CREATE POLICIES TO ALLOW ALL OPERATIONS FOR THIS DEMONSTRATION
CREATE POLICY "Enable all operations for all users on promos" ON "public"."promos" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users on reviews" ON "public"."reviews" FOR ALL USING (true) WITH CHECK (true);

-- INSERT INITIAL MOCK DATA
INSERT INTO "public"."promos" ("code", "discount_type", "discount_value", "usage_count", "status") VALUES
('SUMMER20', 'Percentage', 20.00, 45, 'Active'),
('FREESHIP', 'Fixed', 15.00, 112, 'Active'),
('WELCOME10', 'Percentage', 10.00, 890, 'Expired');

INSERT INTO "public"."reviews" ("customer_name", "product_name", "rating", "comment", "status") VALUES
('Sarah Jenkins', 'Radiant Glow Serum', 5, 'Absolutely love this product! My skin has never looked better.', 'Approved'),
('Michael Chen', 'Hydrating Night Cream', 4, 'Very moisturizing but has a strong scent.', 'Pending');

-- ADD MISSING COLUMNS TO ORDERS TABLE (run in Supabase SQL Editor if not already present)
ALTER TABLE "public"."orders" ADD COLUMN IF NOT EXISTS "phone" text;
ALTER TABLE "public"."orders" ADD COLUMN IF NOT EXISTS "shipping_address" text;
ALTER TABLE "public"."orders" ADD COLUMN IF NOT EXISTS "order_items" jsonb;

-- DATA FIX: Link existing orders to customers by email where customer_id is missing
UPDATE "public"."orders" o
SET "customer_id" = c."id"
FROM "public"."customers" c
WHERE o."email" = c."email" AND o."customer_id" IS NULL;

-- ENSURE IMAGES ARRAY COLUMN EXISTS
ALTER TABLE "public"."products" ADD COLUMN IF NOT EXISTS "images" text[] DEFAULT '{}';

-- STORAGE INSTRUCTIONS (Run in Supabase Dashboard):
-- 1. Create a public bucket named 'product-images'
-- 2. Add a policy to 'Enable insertion for authenticated users only'
-- 3. Add a policy to 'Enable read access for all' (public)

